=== arvindgupta1981/xml-rd/XML-Basic/order.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT order (id,customer,address,taxed,lineitems)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT customer (#PCDATA)>
<!ELEMENT address (#PCDATA) >
<!ELEMENT taxed EMPTY>
<!ELEMENT lineitems (item+)>
<!ELEMENT item (itemid,qty,amount)>
<!ELEMENT itemid (#PCDATA)>
<!ELEMENT qty (#PCDATA)>
<!ELEMENT amount (#PCDATA)>

=== arvindgupta1981/xml-rd/XML-Basic/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE order SYSTEM "order.dtd">
<order>
	<id>#1000$</id>
	<customer>Arvind gupta</customer>
	<address>ABC Indirapuram</address>
	<taxed/>
	<lineitems>
		<item>
			<itemid>X1</itemid>
			<qty>10</qty>
			<amount>1000</amount>
		</item>
		<item>
			<itemid>X2</itemid>
			<qty>30</qty>
			<amount>3300</amount>
		</item>
	</lineitems>
</order>
